matrix:
  allow_failures:
    - os: windows

os:
  - osx
  - linux
  - windows

language: node_js

node_js:
  - node
  - 14
  - 13
  - 10
  - 9
  - 8

cache:
  - npm: true
  - cargo: true

before_install:
  # Install Rust and Cargo
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      choco install rust
    else
      curl https://sh.rustup.rs -sSf > /tmp/rustup.sh && /
      sh /tmp/rustup.sh -y && /
      export PATH="$HOME/.cargo/bin:$PATH" && /
      source "$HOME/.cargo/env"
    fi
  #rust toolchain
  - rustup toolchain uninstall stable
  - rustup toolchain install stable
  - rustup show
  # Install NPM packages
  - node -v
  - npm -v
  - npm install --unsafe-perm=true
script:
  - travis_wait 30 npm run test -- --runInBand
  # Publish when using '[publish binary]' keywords
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then npm run upload-binary || exit 0; fi;
